/**
 * Données d'autocomplétion.
 * Format d'une commande : [nom, gabarit (syntaxe snippet CodeMirror, sans le « \ »), description, math?]
 */
export type CmdSpec = [string, string | null, string, boolean?]

export const COMMANDS: CmdSpec[] = [
  // Structure
  ['documentclass', 'documentclass[${options}]{${article}}', 'Classe du document'],
  ['usepackage', 'usepackage{${paquet}}', 'Charger un paquet'],
  ['usepackage[]', 'usepackage[${options}]{${paquet}}', 'Charger un paquet avec options'],
  ['begin', 'begin{${env}}\n\t${}\n\\end{${env}}', 'Ouvrir un environnement'],
  ['end', 'end{${env}}', 'Fermer un environnement'],
  ['part', 'part{${titre}}', 'Partie'],
  ['chapter', 'chapter{${titre}}', 'Chapitre'],
  ['chapter*', 'chapter*{${titre}}', 'Chapitre non numéroté'],
  ['section', 'section{${titre}}', 'Section'],
  ['section*', 'section*{${titre}}', 'Section non numérotée'],
  ['subsection', 'subsection{${titre}}', 'Sous-section'],
  ['subsection*', 'subsection*{${titre}}', 'Sous-section non numérotée'],
  ['subsubsection', 'subsubsection{${titre}}', 'Sous-sous-section'],
  ['paragraph', 'paragraph{${titre}}', 'Paragraphe'],
  ['subparagraph', 'subparagraph{${titre}}', 'Sous-paragraphe'],
  ['title', 'title{${titre}}', 'Titre du document'],
  ['author', 'author{${auteur}}', 'Auteur(s)'],
  ['date', 'date{${\\today}}', 'Date'],
  ['today', null, 'Date du jour'],
  ['maketitle', null, 'Afficher le titre'],
  ['tableofcontents', null, 'Table des matières'],
  ['listoffigures', null, 'Liste des figures'],
  ['listoftables', null, 'Liste des tableaux'],
  ['appendix', null, 'Début des annexes'],
  ['input', 'input{${fichier}}', 'Inclure un fichier'],
  ['include', 'include{${fichier}}', 'Inclure un chapitre (nouvelle page)'],
  ['newpage', null, 'Nouvelle page'],
  ['clearpage', null, 'Vider les flottants et nouvelle page'],
  ['pagebreak', null, 'Saut de page suggéré'],
  ['linebreak', null, 'Saut de ligne suggéré'],
  ['newline', null, 'Nouvelle ligne'],
  ['noindent', null, 'Pas d’alinéa'],
  ['indent', null, 'Alinéa'],
  ['par', null, 'Fin de paragraphe'],
  ['footnote', 'footnote{${texte}}', 'Note de bas de page'],
  ['marginpar', 'marginpar{${texte}}', 'Note en marge'],
  ['item', 'item ${}', 'Élément de liste'],
  ['item[]', 'item[${label}] ${}', 'Élément avec étiquette'],
  ['label', 'label{${clé}}', 'Étiquette de référence'],
  ['ref', 'ref{${clé}}', 'Référence'],
  ['eqref', 'eqref{${clé}}', 'Référence d’équation'],
  ['pageref', 'pageref{${clé}}', 'Numéro de page d’une référence'],
  ['autoref', 'autoref{${clé}}', 'Référence automatique (hyperref)'],
  ['cref', 'cref{${clé}}', 'Référence intelligente (cleveref)'],
  ['Cref', 'Cref{${clé}}', 'Référence intelligente, majuscule'],
  ['nameref', 'nameref{${clé}}', 'Référence par nom'],
  ['cite', 'cite{${clé}}', 'Citation'],
  ['citep', 'citep{${clé}}', 'Citation entre parenthèses (natbib)'],
  ['citet', 'citet{${clé}}', 'Citation textuelle (natbib)'],
  ['parencite', 'parencite{${clé}}', 'Citation entre parenthèses (biblatex)'],
  ['textcite', 'textcite{${clé}}', 'Citation textuelle (biblatex)'],
  ['autocite', 'autocite{${clé}}', 'Citation automatique (biblatex)'],
  ['nocite', 'nocite{${*}}', 'Ajouter à la bibliographie sans citer'],
  ['bibliography', 'bibliography{${references}}', 'Fichier de bibliographie BibTeX'],
  ['bibliographystyle', 'bibliographystyle{${plain}}', 'Style de bibliographie'],
  ['addbibresource', 'addbibresource{${references.bib}}', 'Ressource biblatex'],
  ['printbibliography', null, 'Imprimer la bibliographie (biblatex)'],
  ['url', 'url{${https://}}', 'URL'],
  ['href', 'href{${https://}}{${texte}}', 'Lien hypertexte'],
  ['includegraphics', 'includegraphics[width=${0.8}\\linewidth]{${image}}', 'Insérer une image'],
  ['caption', 'caption{${légende}}', 'Légende'],
  ['centering', null, 'Centrer'],
  ['hline', null, 'Ligne horizontale (tableau)'],
  ['cline', 'cline{${1}-${2}}', 'Ligne partielle'],
  ['toprule', null, 'Filet supérieur (booktabs)'],
  ['midrule', null, 'Filet intermédiaire (booktabs)'],
  ['bottomrule', null, 'Filet inférieur (booktabs)'],
  ['multicolumn', 'multicolumn{${2}}{${c}}{${texte}}', 'Fusion de colonnes'],
  ['multirow', 'multirow{${2}}{*}{${texte}}', 'Fusion de lignes'],
  ['newcommand', 'newcommand{\\${nom}}[${0}]{${définition}}', 'Définir une commande'],
  ['renewcommand', 'renewcommand{\\${nom}}{${définition}}', 'Redéfinir une commande'],
  ['newenvironment', 'newenvironment{${nom}}{${début}}{${fin}}', 'Définir un environnement'],
  ['newtheorem', 'newtheorem{${theorem}}{${Théorème}}', 'Définir un théorème'],
  ['DeclareMathOperator', 'DeclareMathOperator{\\${nom}}{${texte}}', 'Opérateur mathématique'],
  ['setlength', 'setlength{\\${parindent}}{${0pt}}', 'Fixer une longueur'],
  ['vspace', 'vspace{${1em}}', 'Espace vertical'],
  ['hspace', 'hspace{${1em}}', 'Espace horizontal'],
  ['vfill', null, 'Remplissage vertical'],
  ['hfill', null, 'Remplissage horizontal'],
  ['quad', null, 'Espace cadratin'],
  ['qquad', null, 'Double cadratin'],
  ['smallskip', null, 'Petit saut vertical'],
  ['medskip', null, 'Saut vertical moyen'],
  ['bigskip', null, 'Grand saut vertical'],
  // Mise en forme du texte
  ['textbf', 'textbf{${texte}}', 'Gras'],
  ['textit', 'textit{${texte}}', 'Italique'],
  ['emph', 'emph{${texte}}', 'Mise en évidence'],
  ['underline', 'underline{${texte}}', 'Souligné'],
  ['texttt', 'texttt{${texte}}', 'Police à chasse fixe'],
  ['textsc', 'textsc{${texte}}', 'Petites capitales'],
  ['textsf', 'textsf{${texte}}', 'Sans empattement'],
  ['textrm', 'textrm{${texte}}', 'Romain'],
  ['textsl', 'textsl{${texte}}', 'Penché'],
  ['textcolor', 'textcolor{${red}}{${texte}}', 'Texte en couleur'],
  ['colorbox', 'colorbox{${yellow}}{${texte}}', 'Fond coloré'],
  ['fbox', 'fbox{${texte}}', 'Texte encadré'],
  ['mbox', 'mbox{${texte}}', 'Boîte insécable'],
  ['tiny', null, 'Taille minuscule'],
  ['scriptsize', null, 'Taille très petite'],
  ['footnotesize', null, 'Taille note'],
  ['small', null, 'Petite taille'],
  ['normalsize', null, 'Taille normale'],
  ['large', null, 'Grand'],
  ['Large', null, 'Plus grand'],
  ['LARGE', null, 'Très grand'],
  ['huge', null, 'Énorme'],
  ['Huge', null, 'Gigantesque'],
  ['LaTeX', null, 'Logo LaTeX'],
  ['TeX', null, 'Logo TeX'],
  ['ldots', null, 'Points de suspension'],
  ['verb', 'verb|${code}|', 'Verbatim en ligne'],
  // Maths
  ['frac', 'frac{${num}}{${den}}', 'Fraction', true],
  ['dfrac', 'dfrac{${num}}{${den}}', 'Fraction (grande)', true],
  ['tfrac', 'tfrac{${num}}{${den}}', 'Fraction (petite)', true],
  ['sqrt', 'sqrt{${x}}', 'Racine carrée', true],
  ['sqrt[]', 'sqrt[${n}]{${x}}', 'Racine n-ième', true],
  ['sum', 'sum_{${i=1}}^{${n}}', 'Somme', true],
  ['prod', 'prod_{${i=1}}^{${n}}', 'Produit', true],
  ['int', 'int_{${a}}^{${b}} ${f(x)} \\,\\mathrm{d}${x}', 'Intégrale', true],
  ['iint', 'iint', 'Intégrale double', true],
  ['oint', 'oint', 'Intégrale curviligne', true],
  ['lim', 'lim_{${x \\to \\infty}}', 'Limite', true],
  ['binom', 'binom{${n}}{${k}}', 'Coefficient binomial', true],
  ['left(', 'left( ${} \\right)', 'Parenthèses adaptatives', true],
  ['left[', 'left[ ${} \\right]', 'Crochets adaptatifs', true],
  ['left\\{', 'left\\\\{ ${} \\right\\\\}', 'Accolades adaptatives', true],
  ['left|', 'left| ${} \\right|', 'Barres adaptatives', true],
  ['langle', 'langle ${} \\rangle', 'Chevrons', true],
  ['mathbb', 'mathbb{${R}}', 'Ajouré (ℝ, ℕ…)', true],
  ['mathcal', 'mathcal{${A}}', 'Calligraphique', true],
  ['mathfrak', 'mathfrak{${g}}', 'Gothique', true],
  ['mathscr', 'mathscr{${F}}', 'Cursive', true],
  ['mathbf', 'mathbf{${x}}', 'Gras mathématique', true],
  ['mathrm', 'mathrm{${d}}', 'Romain mathématique', true],
  ['mathit', 'mathit{${x}}', 'Italique mathématique', true],
  ['boldsymbol', 'boldsymbol{${x}}', 'Symbole gras', true],
  ['text', 'text{${texte}}', 'Texte dans une formule', true],
  ['operatorname', 'operatorname{${op}}', 'Nom d’opérateur', true],
  ['hat', 'hat{${x}}', 'Accent circonflexe', true],
  ['widehat', 'widehat{${xy}}', 'Chapeau large', true],
  ['bar', 'bar{${x}}', 'Barre', true],
  ['overline', 'overline{${x}}', 'Surligné', true],
  ['underbrace', 'underbrace{${x}}_{${texte}}', 'Accolade inférieure', true],
  ['overbrace', 'overbrace{${x}}^{${texte}}', 'Accolade supérieure', true],
  ['vec', 'vec{${v}}', 'Vecteur', true],
  ['overrightarrow', 'overrightarrow{${AB}}', 'Vecteur (flèche longue)', true],
  ['dot', 'dot{${x}}', 'Dérivée (point)', true],
  ['ddot', 'ddot{${x}}', 'Dérivée seconde', true],
  ['tilde', 'tilde{${x}}', 'Tilde', true],
  ['widetilde', 'widetilde{${xy}}', 'Tilde large', true],
  ['partial', null, 'Dérivée partielle ∂', true],
  ['nabla', null, 'Nabla ∇', true],
  ['infty', null, 'Infini ∞', true],
  ['cdot', null, 'Point médian ·', true],
  ['cdots', null, 'Points centrés ⋯', true],
  ['vdots', null, 'Points verticaux ⋮', true],
  ['ddots', null, 'Points diagonaux ⋱', true],
  ['times', null, 'Multiplication ×', true],
  ['div', null, 'Division ÷', true],
  ['pm', null, 'Plus ou moins ±', true],
  ['mp', null, 'Moins ou plus ∓', true],
  ['leq', null, 'Inférieur ou égal ≤', true],
  ['geq', null, 'Supérieur ou égal ≥', true],
  ['neq', null, 'Différent ≠', true],
  ['approx', null, 'Environ ≈', true],
  ['equiv', null, 'Équivalent ≡', true],
  ['sim', null, 'Similaire ∼', true],
  ['simeq', null, '≃', true],
  ['propto', null, 'Proportionnel ∝', true],
  ['in', null, 'Appartient ∈', true],
  ['notin', null, 'N’appartient pas ∉', true],
  ['subset', null, 'Inclus ⊂', true],
  ['subseteq', null, 'Inclus ou égal ⊆', true],
  ['supset', null, 'Contient ⊃', true],
  ['cup', null, 'Union ∪', true],
  ['cap', null, 'Intersection ∩', true],
  ['bigcup', 'bigcup_{${i}}', 'Grande union', true],
  ['bigcap', 'bigcap_{${i}}', 'Grande intersection', true],
  ['emptyset', null, 'Ensemble vide ∅', true],
  ['varnothing', null, 'Ensemble vide ∅', true],
  ['forall', null, 'Pour tout ∀', true],
  ['exists', null, 'Il existe ∃', true],
  ['neg', null, 'Négation ¬', true],
  ['land', null, 'Et logique ∧', true],
  ['lor', null, 'Ou logique ∨', true],
  ['implies', null, 'Implique ⟹', true],
  ['iff', null, 'Équivaut ⟺', true],
  ['to', null, 'Flèche →', true],
  ['mapsto', null, '↦', true],
  ['rightarrow', null, '→', true],
  ['leftarrow', null, '←', true],
  ['Rightarrow', null, '⇒', true],
  ['Leftarrow', null, '⇐', true],
  ['Leftrightarrow', null, '⇔', true],
  ['longrightarrow', null, '⟶', true],
  ['xrightarrow', 'xrightarrow{${texte}}', 'Flèche annotée', true],
  ['circ', null, 'Composition ∘', true],
  ['otimes', null, '⊗', true],
  ['oplus', null, '⊕', true],
  ['perp', null, '⊥', true],
  ['parallel', null, '∥', true],
  ['angle', null, '∠', true],
  ['ell', null, 'ℓ', true],
  ['hbar', null, 'ℏ', true],
  ['Re', null, 'Partie réelle', true],
  ['Im', null, 'Partie imaginaire', true],
  ['sin', null, 'Sinus', true],
  ['cos', null, 'Cosinus', true],
  ['tan', null, 'Tangente', true],
  ['arcsin', null, 'Arc sinus', true],
  ['arccos', null, 'Arc cosinus', true],
  ['arctan', null, 'Arc tangente', true],
  ['sinh', null, 'Sinus hyperbolique', true],
  ['cosh', null, 'Cosinus hyperbolique', true],
  ['exp', null, 'Exponentielle', true],
  ['ln', null, 'Logarithme népérien', true],
  ['log', null, 'Logarithme', true],
  ['det', null, 'Déterminant', true],
  ['dim', null, 'Dimension', true],
  ['ker', null, 'Noyau', true],
  ['max', null, 'Maximum', true],
  ['min', null, 'Minimum', true],
  ['sup', null, 'Borne supérieure', true],
  ['inf', null, 'Borne inférieure', true],
  ['gcd', null, 'PGCD', true],
  ['mod', null, 'Modulo', true],
  ['pmod', 'pmod{${n}}', 'Modulo (parenthèses)', true],
  ['displaystyle', null, 'Style « display »', true],
  ['tag', 'tag{${1}}', 'Étiquette d’équation', true],
  ['nonumber', null, 'Pas de numéro', true],
  ['notag', null, 'Pas de numéro', true],
  ['intertext', 'intertext{${texte}}', 'Texte entre lignes d’alignement', true],
  ['alpha', null, 'α', true], ['beta', null, 'β', true], ['gamma', null, 'γ', true], ['Gamma', null, 'Γ', true],
  ['delta', null, 'δ', true], ['Delta', null, 'Δ', true], ['epsilon', null, 'ϵ', true], ['varepsilon', null, 'ε', true],
  ['zeta', null, 'ζ', true], ['eta', null, 'η', true], ['theta', null, 'θ', true], ['Theta', null, 'Θ', true],
  ['vartheta', null, 'ϑ', true], ['iota', null, 'ι', true], ['kappa', null, 'κ', true], ['lambda', null, 'λ', true],
  ['Lambda', null, 'Λ', true], ['mu', null, 'μ', true], ['nu', null, 'ν', true], ['xi', null, 'ξ', true],
  ['Xi', null, 'Ξ', true], ['pi', null, 'π', true], ['Pi', null, 'Π', true], ['rho', null, 'ρ', true],
  ['varrho', null, 'ϱ', true], ['sigma', null, 'σ', true], ['Sigma', null, 'Σ', true], ['tau', null, 'τ', true],
  ['upsilon', null, 'υ', true], ['phi', null, 'ϕ', true], ['varphi', null, 'φ', true], ['Phi', null, 'Φ', true],
  ['chi', null, 'χ', true], ['psi', null, 'ψ', true], ['Psi', null, 'Ψ', true], ['omega', null, 'ω', true],
  ['Omega', null, 'Ω', true],
  // Beamer / TikZ
  ['frametitle', 'frametitle{${titre}}', 'Titre de diapositive'],
  ['pause', null, 'Pause (beamer)'],
  ['only', 'only<${2}>{${contenu}}', 'Contenu visible sur certaines diapositives'],
  ['usetheme', 'usetheme{${Madrid}}', 'Thème beamer'],
  ['draw', 'draw ${(0,0)} -- ${(1,1)};', 'Tracer (TikZ)'],
  ['node', 'node[${}] at (${0,0}) {${texte}};', 'Nœud (TikZ)'],
  ['fill', 'fill[${blue}] ${(0,0)} circle (${1pt});', 'Remplir (TikZ)']
]

/** Environnements : [nom, contenu par défaut (snippet), description, argument supplémentaire] */
export type EnvSpec = [string, string, string, string?]

export const ENVIRONMENTS: EnvSpec[] = [
  ['document', '${}', 'Corps du document'],
  ['abstract', '${}', 'Résumé'],
  ['itemize', '\\item ${}', 'Liste à puces'],
  ['enumerate', '\\item ${}', 'Liste numérotée'],
  ['description', '\\item[${terme}] ${}', 'Liste de définitions'],
  ['equation', '${}', 'Équation numérotée'],
  ['equation*', '${}', 'Équation non numérotée'],
  ['align', '${a} &= ${b} \\\\\n\t${c} &= ${d}', 'Équations alignées'],
  ['align*', '${a} &= ${b}', 'Équations alignées sans numéro'],
  ['gather', '${}', 'Équations centrées'],
  ['gather*', '${}', 'Équations centrées sans numéro'],
  ['multline', '${}', 'Équation sur plusieurs lignes'],
  ['split', '${}', 'Découpage d’équation'],
  ['cases', '${a} & \\text{si } ${x} \\\\\n\t${b} & \\text{sinon}', 'Définition par cas'],
  ['matrix', '${a} & ${b} \\\\ ${c} & ${d}', 'Matrice'],
  ['pmatrix', '${a} & ${b} \\\\ ${c} & ${d}', 'Matrice (parenthèses)'],
  ['bmatrix', '${a} & ${b} \\\\ ${c} & ${d}', 'Matrice (crochets)'],
  ['vmatrix', '${a} & ${b} \\\\ ${c} & ${d}', 'Déterminant'],
  ['figure', '\\centering\n\t\\includegraphics[width=${0.8}\\linewidth]{${image}}\n\t\\caption{${légende}}\n\t\\label{fig:${clé}}', 'Figure flottante', '[htbp]'],
  ['table', '\\centering\n\t\\caption{${légende}}\n\t\\label{tab:${clé}}\n\t\\begin{tabular}{${lll}}\n\t\t${}\n\t\\end{tabular}', 'Tableau flottant', '[htbp]'],
  ['tabular', '${a} & ${b} \\\\\n\t${c} & ${d} \\\\', 'Tableau', '{${ll}}'],
  ['center', '${}', 'Centrer'],
  ['flushleft', '${}', 'Aligner à gauche'],
  ['flushright', '${}', 'Aligner à droite'],
  ['quote', '${}', 'Citation courte'],
  ['quotation', '${}', 'Citation longue'],
  ['verbatim', '${}', 'Texte brut'],
  ['minipage', '${}', 'Mini-page', '{${0.45}\\linewidth}'],
  ['theorem', '${}', 'Théorème'],
  ['lemma', '${}', 'Lemme'],
  ['proposition', '${}', 'Proposition'],
  ['corollary', '${}', 'Corollaire'],
  ['definition', '${}', 'Définition'],
  ['remark', '${}', 'Remarque'],
  ['example', '${}', 'Exemple'],
  ['proof', '${}', 'Démonstration'],
  ['frame', '\\frametitle{${titre}}\n\t${}', 'Diapositive (beamer)'],
  ['block', '${}', 'Bloc (beamer)', '{${titre}}'],
  ['columns', '\\column{0.5\\textwidth}\n\t${}\n\t\\column{0.5\\textwidth}\n\t', 'Colonnes (beamer)'],
  ['tikzpicture', '\\draw ${(0,0)} -- (1,1);', 'Dessin TikZ'],
  ['lstlisting', '${}', 'Code source (listings)'],
  ['minted', '${}', 'Code source (minted)', '{${python}}'],
  ['thebibliography', '\\bibitem{${clé}} ${référence}', 'Bibliographie manuelle', '{99}'],
  ['subfigure', '${}', 'Sous-figure', '{${0.45}\\linewidth}']
]

export const PACKAGES: [string, string][] = [
  ['amsmath', 'Mathématiques avancées (AMS)'],
  ['amssymb', 'Symboles AMS'],
  ['amsthm', 'Théorèmes'],
  ['mathtools', 'Extensions d’amsmath'],
  ['graphicx', 'Images'],
  ['hyperref', 'Liens hypertexte'],
  ['geometry', 'Mise en page / marges'],
  ['babel', 'Langues'],
  ['polyglossia', 'Langues (XeLaTeX)'],
  ['fontspec', 'Polices OpenType (XeLaTeX)'],
  ['xcolor', 'Couleurs'],
  ['tikz', 'Dessins'],
  ['pgfplots', 'Graphiques'],
  ['booktabs', 'Beaux tableaux'],
  ['tabularx', 'Tableaux à largeur fixe'],
  ['longtable', 'Tableaux sur plusieurs pages'],
  ['multirow', 'Fusion de lignes'],
  ['array', 'Colonnes de tableau avancées'],
  ['siunitx', 'Unités et nombres'],
  ['caption', 'Légendes personnalisées'],
  ['subcaption', 'Sous-figures'],
  ['float', 'Placement des flottants'],
  ['enumitem', 'Listes personnalisées'],
  ['fancyhdr', 'En-têtes et pieds de page'],
  ['titlesec', 'Titres de sections'],
  ['cleveref', 'Références intelligentes'],
  ['natbib', 'Citations auteur-année'],
  ['biblatex', 'Bibliographie moderne'],
  ['csquotes', 'Guillemets'],
  ['listings', 'Code source'],
  ['minted', 'Code source coloré'],
  ['microtype', 'Micro-typographie'],
  ['setspace', 'Interligne'],
  ['parskip', 'Espacement des paragraphes'],
  ['lipsum', 'Faux texte'],
  ['blindtext', 'Faux texte'],
  ['tcolorbox', 'Boîtes colorées'],
  ['physics', 'Notations physiques'],
  ['mhchem', 'Formules chimiques'],
  ['algorithm2e', 'Algorithmes'],
  ['algorithmicx', 'Algorithmes'],
  ['todonotes', 'Notes à faire'],
  ['url', 'URL'],
  ['wrapfig', 'Figures habillées'],
  ['pdfpages', 'Inclure des PDF'],
  ['multicol', 'Plusieurs colonnes'],
  ['xparse', 'Définitions de commandes'],
  ['etoolbox', 'Outils de programmation'],
  ['lmodern', 'Latin Modern'],
  ['stmaryrd', 'Symboles supplémentaires'],
  ['bm', 'Gras mathématique'],
  ['dsfont', 'Lettres ajourées'],
  ['esint', 'Intégrales'],
  ['cancel', 'Barrer des termes'],
  ['chemfig', 'Formules chimiques développées'],
  ['circuitikz', 'Circuits électriques'],
  ['forest', 'Arbres']
]

export const CLASSES: [string, string][] = [
  ['article', 'Article'],
  ['report', 'Rapport'],
  ['book', 'Livre'],
  ['beamer', 'Présentation'],
  ['letter', 'Lettre'],
  ['memoir', 'Mémoire (classe flexible)'],
  ['scrartcl', 'Article KOMA-Script'],
  ['scrreprt', 'Rapport KOMA-Script'],
  ['scrbook', 'Livre KOMA-Script'],
  ['scrlttr2', 'Lettre KOMA-Script'],
  ['standalone', 'Figure autonome'],
  ['moderncv', 'CV'],
  ['exam', 'Examen']
]
